amapp/urls.py
from django.db.models.query import ValuesIterable
from django.urls import path
from . import views

app_name = 'amapp'
urlpatterns=[
    path('', views.index, name='home'),
    path('login', views.LoginView.as_view(), name='login'),
    path('logout', views.logout_view, name='logout'),
    path('admin-dashboard', views.admin_dashboard, name='admin_dashboard'),
    path('register-dashboard/<int:pk>', views.RegisterDashboard.as_view(), name='register_dashboard'),
    path('mysessions/<int:pk>', views.SessionListView.as_view(), name='my_sessions'),
    path('session_details/<int:pk>/<int:sid>',views.SessionDetailsView.as_view(),name='session_details'),
    path('addstudent',views.addstudent, name='addstudent'),
    path('createregister', views.CreateRegisterView.as_view(), name='create_register'),
    path('start_session',views.start_session, name='start-session'),
]

ams/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('amapp.urls')),
]

amapp/models.py
from os import name, truncate
from django.db import models
from django.db.models.deletion import CASCADE, SET_NULL

# Create your models here.
class Student(models.Model):
    first_name = models.CharField(max_length= 50)
    last_name = models.CharField(max_length= 50)
    other_names = models.CharField(max_length= 50)
    mat_no = models.CharField(max_length=10)
    email = models.EmailField()
    department = models.CharField(max_length=20)
    level = models.IntegerField()
    fingerprintId = models.IntegerField(null=True)


    def __str__(self):
            return self.last_name+' '+self.first_name+' '+self.other_names


class Register(models.Model):
    name = models.CharField(max_length=10, unique=True)
    reg_id = models.CharField(max_length=10, unique=True)
    email = models.EmailField()
    password = models.CharField(max_length=250)


    def __str__(self):
            return self.name


class Session(models.Model):
    title = models.CharField(max_length=15)
    date = models.DateField()
    start = models.TimeField()
    end = models.TimeField()
    register = models.ForeignKey(to=Register, on_delete=CASCADE)
    attendees = models.ManyToManyField(Student, blank=True)
    session_id = models.CharField(max_length=10, unique=True)

    def __str__(self):
            return self.title+' '+str(self.date)

amapp/views.py
import string
import random
from datetime import datetime

from django import contrib
from django.http import HttpResponse
from django.http.response import Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View, generic
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import make_password, check_password
from django.utils.decorators import method_decorator
from django.db import IntegrityError

from amapp import models
import amapp
from .decorators import register_signin_required
from .models import Register, Session

# Create your views here.
def index(request):
    return render(request, template_name='amapp/index.html')


class LoginView(View):
    def get(self,request):
        return render(request, template_name='amapp/login.html');

    def post(self,request):
        username=request.POST['username']
        password=request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            # print(user)
            # print(request.session['_auth_user_id'])
            return redirect('amapp:admin_dashboard')
        else:
            try:
                register = get_object_or_404(Register,name=username, password=password)
                request.session['register_id'] = register.id
                return redirect('amapp:register_dashboard', pk=register.id)
            except Http404:
                messages.error(request, 'Invalid credentials')
                return render(request, template_name='amapp/login.html')


def logout_view(request):
    logout(request)
    return redirect('amapp:home')


@login_required
def admin_dashboard(request):
    return render(request, template_name='amapp/admin_dashboard.html')


@method_decorator(register_signin_required, name='dispatch')
class RegisterDashboard(generic.DetailView):
    model= Register
    template_name='amapp/dashboard.html'
    
    def __init__(self, **kwargs) -> None:
        super().__init__(**kwargs)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        id = self.kwargs['pk']
        session_count = Session.objects.filter(register_id=id).count()
        context['session_count']=session_count
        return context


@method_decorator(register_signin_required, name='dispatch')
class SessionListView(generic.ListView):
    model = Session
    template_name = 'amapp/mysessions.html'
    context_object_name = 'Context'

    def get_queryset(self):
        register = Register.objects.get(id = self.kwargs['pk'])
        sessions = Session.objects.filter(register_id=self.kwargs['pk']).order_by('id').reverse()
        context = {'Register':register, 'Sessions':sessions}
        print(context)
        return context


@method_decorator(register_signin_required, name='dispatch')
class SessionDetailsView(generic.DetailView):
    model = Session
    template_name = 'amapp/session_details.html'
    context_object_name = 'session'
    
    # def get_queryset(self):
    #     session = Session.objects.get(id = self.kwargs['sid'])
    #     attendees = 


def addstudent(request):
    return render(request, template_name='amapp/addstudent1.html')


class CreateRegisterView(View):
    def get(self,request):
        return render(request, template_name='amapp/create_register.html');

    def post(self,request):
        reg_name=request.POST['reg_name']
        email=request.POST['email']
        password1=request.POST['password1']
        password2=request.POST['password2']

        if password1 == password2:
            try:
                new_register = Register(name=reg_name, email=email, password=make_password(password1))
                new_register.save()
                # reg_id generation
                id_plus_year = 'reg'+str(new_register.id)+'d'+str(datetime.now().date().year)[2:]
                n = len(id_plus_year)
                new_register.reg_id =id_plus_year+''.join(random.choices(string.ascii_uppercase + string.digits, k=10-n))
                new_register.save()
                messages.success(request, 'Register created successfully!')
                request.session['register_id'] = new_register.id
                return redirect('amapp:register_dashboard', pk=new_register.id)
            except IntegrityError:
                messages.error(request, "the given registername already exists.")
                return render(request, template_name='amapp/create_register.html');
        else:
            messages.error(request, 'Passwords do not match')
            return render(request, template_name='amapp/create_register.html');



def  start_session(request):
    if request.method == 'POST':
        reg_name = request.POST['register-name']
        device_id = request.POST['device-id']
        title = request.POST['title']
        start_time = request.POST['start-time']
        end_time = request.POST['end-time']
        password = request.POST['password']
        date = datetime.now().date()
        
        register = Register.objects.get(name = reg_name)
        new_session = Session(title = title,date = date,start = start_time,\
            end = end_time,register = register)
        new_session.save()
        return HttpResponse('got the form')

amapp/templates/amapp/admin_dashboard.html
{% extends 'amapp/base.html' %}
{% block title %}AMS-dashboard{% endblock %}
{% block dashboard-active %}class="nav-item active"{% endblock %}
{% block content %}
    <main>
        <div class="flex-container">
            <div id="sidebar" class="collapse show">
                <div class="sidenav-item">
                    <a href="#">
                        <div class="sidenav-active my-4">
                            <i class="fas fa-tachometer-alt"></i>
                            <h6>Dashboard</h6>
                        
                            
                        </div>
                    </a>
                </div>
                <div class="sidenav-item my-4">
                    <a href="#">
                        <div>
                            <i class="fas fa-calendar-alt"></i>
                            <h6>Sessions</h6>
                        </div>
                    </a>
                </div>
                <div class="sidenav-item my-4">
                    <a href="#">
                        <div>
                            <i class="fas fa-address-card"></i>
                            <h6>Students</h6>
                        </div>
                    </a>
                </div>
                <div class="sidenav-item my-4">
                    <a href="{% url 'amapp:addstudent'%}">
                        <div>
                            <i class="fas fa-user-plus"></i>
                            <h6>Add student</h6>
                        </div>
                    </a>
                </div>
                <div class="sidenav-item my-4">
                    <a href="{% url 'amapp:create_register'%}">
                        <div>
                            <i class="fas fa-user-plus"></i>
                            <h6>Create Register</h6>
                        </div>
                    </a>
                </div>
            </div>
            <div id="workspace">
                <div class="row">
                    <div class="col-6">
                        <h2>{{user.username}}</h2>
                        <h6>Register Id:&nbsp;<span class="blue">cpx4xio34ad</span></h6>
                    </div>
                    <div class="col-6 my-sm-4">
                        <button class="btn btn-primary float-right mx-sm-4" data-toggle="modal" data-target="#exampleModalCenter">Start a session&nbsp;<i class="fa fa-arrow-right" aria-hidden="true"></i></button>
                    </div>
                </div>
                <div>
                    <h6 class="buttonlike col-xl-3 col-md-5 col-sm-6 mt-3">Active sessions <span class="red">. . .</span></h6>
                </div>
                <table class="table table-hover table-responsive-sm">
                    <caption>List of currently active sessions</caption>
                    <thead>
                        <tr>
                            <th scope="col">s/n</th>
                            <th scope="col">Register</th>
                            <th scope="col">Rgstr Id</th>
                            <th scope="col">Start</th>
                            <th scope="col">End</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <th scope="row">1</th>
                            <td>CPE 547</td>
                            <td>rhgnt50403</td>
                            <td>10:05 AM</td>
                            <td>01:00 PM</td>
                            <td><a href="#">View</a></td>
                        </tr>          
                        <tr>
                            <th scope="row">2</th>
                            <td>CPE 547</td>
                            <td>rhgnt50403</td>
                            <td>10:05 AM</td>
                            <td>01:00 PM</td>
                            <td><a href="#">View</a></td>
                        </tr> 
 
                                    
                    </tbody>
                </table>

            </div> 
        </div>
        <!------- Modal ----------->
        <div class="modal fade bd-example-modal-xl" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered modal-xl" role="document">
                <div class="modal-content">
                    <div class="row">
                        <div class="home col-lg-4">
                            <h1>ATTENDANCE<br><span class="smaller">MANAGEMENT</span><br>SYSTEM</h1>
                        </div>
                        <div class="home-right col-lg-8">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            <p class="buttonlike col-md-6 offset-md-3 mb-4">Start a session</p>
                            <form action="#">
                            <div class="form-group">
                                <input type="text" placeholder="Register Name" class="form-control">
                            </div>
                            <div class="form-group">
                                <input type="text" placeholder="Devide Id" class="form-control">
                            </div>
                            <div class="form-group">
                                <input type="password" placeholder="Password" class="form-control">
                            </div>
                            <div class="form-row">
                                <div class="form-group col-sm-6">
                                    <label for="start-time">Start time</label>
                                    <input type="time" placeholder="Start time" class="form-control" id="start-time">
                                </div>
                                <div class="form-group col-sm-6">
                                    <label for="end-time">End time</label>
                                    <input type="time" placeholder="End time" class="form-control" id="end-time">
                                </div>
                              </div>
                            <button type="submit" class="btn btn-primary">Start &nbsp;<i class="fa fa-arrow-right" aria-hidden="true"></i></button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

amapp/templates/amapp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- {# bootstrap #} -->
    <link rel="stylesheet" href="{% static 'bootstrap-4.5.0-dist/css/bootstrap.min.css' %}">

    <!-- Jquery -->
    <script src="{% static 'jquery/jquery-3.3.1.min.js' %}"></script>
    <!-- Bootstrap -->
    <script src="{% static 'bootstrap-4.5.0-dist/js/bootstrap.min.js' %}"></script>
    <!-- Font Awesome JS -->
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js" integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js" integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous"></script>
    <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"> -->
    <script defer src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/solid.min.js"></script>

    <link rel="stylesheet" href="{% static 'amapp/css/style.css' %}">
    {% block extrastyles %}{% endblock %}
    <title>{% block title %}AMS{% endblock %}</title>
</head>
<body>
  <nav class=" navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
    <a class="navbar-brand" href="/">AMS</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
          <li {% block home-active %}{% endblock %}>
            <a class="nav-link" href="{% url 'amapp:home'%}">Home</a>
          </li>
          {% if user.is_authenticated or 'register_id' in request.session %}
            <li {% block dashboard-active %}{% endblock %}>
              <a class="nav-link" href="{% if user.is_authenticated %} {% url 'amapp:admin_dashboard' %}{% else %}{% url 'amapp:register_dashboard' request.session.register_id %}{% endif %}">Dashboard</a>
            </li>
            <li>
              <a class="nav-link" href="{% url 'amapp:logout'%}">Logout &nbsp;<i class="fas fa-sign-out-alt"></i></a>
            </li>
          {% else %}
            <li {% block login-active %}{% endblock %}>
              <a class="nav-link" href="{% url 'amapp:login'%}">Login &nbsp;<i class="fas fa-sign-in-alt"></i></a>
            </li>
          {% endif %}
          
      </ul>
    </div>
  </nav>
  <main>
    <!-- flash messages -->
    {% if messages %}
      <ul class="messages">
          {% for message in messages %}
          <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
          {% endfor %}
      </ul>
    {% endif %}

    {% block content %}{% endblock %}
  </main>
  <footer>
    <p>&copy;Copyright 2021</p>
  </footer>

  <!-- Popper.JS -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
  <script src="{% static 'amapp/js/script.js' %}""></script>
</body>
</html>

amapp/templates/amapp/create_register.html
{% extends 'amapp/base.html' %}
{% block title %}AMS-Create Register{% endblock %}
{% block dashboard-active %}class="nav-item active"{% endblock %}
{% block content %}
    <main>
        <div class="flex-container">
            <div id="sidebar" class="collapse show">
                <div class="sidenav-item">
                    <a href="#">
                        <div class="sidenav-active my-4">
                            <i class="fas fa-tachometer-alt"></i>
                            <h6>Dashboard</h6>
                        </div>
                    </a>
                </div>
                <div class="sidenav-item my-4">
                    <a href="#">
                        <div>
                            <i class="fas fa-calendar-alt"></i>
                            <h6>Sessions</h6>
                        </div>
                    </a>
                </div>
                <div class="sidenav-item my-4">
                    <a href="#">
                        <div>
                            <i class="fas fa-address-card"></i>
                            <h6>Students</h6>
                        </div>
                    </a>
                </div>
                <div class="sidenav-item my-4">
                    <a href="#">
                        <div>
                            <i class="fas fa-user-plus"></i>
                            <h6>Add student</h6>
                        </div>
                    </a>
                </div>
                <div class="sidenav-item my-4">
                    <a href="{% url 'amapp:create_register'%}">
                        <div>
                            <i class="fas fa-user-plus"></i>
                            <h6>Create Register</h6>
                        </div>
                    </a>
                </div>
            </div>
            <div id="workspace">
                <div class="row heading-ve-margn">
                    <div class="col-6 offset-3 my-sm-4 ">
                        <button class="btn btn-primary ml-auto mx-sm-4">Create Register&nbsp;</button>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-7 offset-md-3 card cred">
                        <form action="{% url 'amapp:create_register' %}" method="POST">
                            {% csrf_token %}
                            <div class="form-group">
                              <input name='reg_name' type="text" placeholder="Register Name" class="form-control">
                            </div>

                            <div class="form-group">
                                <input name='email' type="email" placeholder="Email" class="form-control">
                            </div>

                            <div class="form-group">
                                <input name='password1' type="password" placeholder="Password" class="form-control">
                            </div>
                            
                            <div class="form-group">
                                <input name='password2' type="password" placeholder="Confirm password" class="form-control">
                            </div>
                            <button type="submit" class="btn btn-primary mr-auto" id="submit-btn">Create &nbsp;<i class="fa fa-arrow-right" aria-hidden="true"></i></button>
                        </form>
                    </div>
                </div>
                
            </div> 
        </div>
    </main>
{% endblock %}

amapp/templates/amapp/index.html
{% extends 'amapp/base.html' %}

{% block title %}AMS-Home{% endblock %}
{% block home-active %}class=" nav-item active"{% endblock %}
{% block content %}
  <div class="container">
    <div class="card" id="home-card">
      <div class="row">
        <div class="home col-lg-4">
          <h1>ATTENDANCE<br><span class="smaller">MANAGEMENT</span><br>SYSTEM</h1>
        </div>
        <div class="home-right col-lg-8">
          <p class="buttonlike col-md-6 offset-md-3 mb-4">Start a session</p>
          <form method="POST" action="{% url 'amapp:start-session'%}">
            {% csrf_token %}
            <div class=form-row>
              <div class="form-group col-sm-6">
                <input name="register-name" type="text" placeholder="Register Name" class="form-control">
              </div>
              <div class="form-group col-sm-6">
                <input name="device-id" type="text" placeholder="Devide Id" class="form-control">
              </div>
            </div>
            <div class="form-group">
              <input name="title" type="text" placeholder="Title" class="form-control">
            </div>
            <div class="form-row">
              <div class="form-group col-sm-6">
                  <label for="start-time">Start time</label>
                  <input name="start-time" type="time" placeholder="Start time" class="form-control" id="start-time">
              </div>
              <div class="form-group col-sm-6">
                  <label for="end-time">End time</label>
                  <input name="end-time" type="time" placeholder="End time" class="form-control" id="end-time">
              </div>
            </div>
            <div class="form-group">
              <input name="password" type="password" placeholder="Register Password" class="form-control">
            </div>
            <button type="submit" class="btn btn-primary mr-auto">Start &nbsp;<i class="fa fa-arrow-right" aria-hidden="true"></i></button>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

amapp/templates/amapp/login.html
{% extends 'amapp/base.html' %}
{% block title %}AMS-Login{% endblock %}
{% block login-active %}class="nav-item active"{% endblock %}
{% block content %}
  <div class="container">
    <main>
        <div class="tiles" id="tile1"></div>
        <div class="tiles" id="tile2"></div>
        <div class="tiles" id="tile3"></div>
        <div class="login-form col-10 offset-1 col-md-8 offset-md-2 col-lg-6 offset-lg-3">
            <h3>Login</h3>
            <small>Enter username <span class="red">or</span> register name to login</small>
            <form action="{% url 'amapp:login'%}" method="POST">
                {% csrf_token %}
                <div class="form-group">
                <input type="text" name="username" placeholder="Username or Reg Name" class="form-control">
                </div>
                <div class="form-group">
                <input type="password" name="password" placeholder="Password" class="form-control">
                </div>
                <button type="submit" class="btn btn-primary">Login &nbsp;<i class="fa fa-arrow-right" aria-hidden="true"></i></button>
            </form>
        </div>
    </main>
  </div>
{% endblock %}

amapp/templates/amapp/mysessions.html
{% extends 'amapp/base.html' %}
{% block title %}AMS-Sessions{% endblock %}
{% block dashboard-active %}class="nav-item active"{% endblock %}
{% block content %}
    <main>
        <div class="flex-container">
        <div id="sidebar" class="collapse show">
            <div class="sidenav-item">
                <a href="{% url 'amapp:register_dashboard' request.session.register_id %}">
                    <div class="my-4">
                        <i class="fas fa-tachometer-alt"></i>
                        <h6>Dashboard</h6>
                    </div>
                </a>
            </div>
            <div class="sidenav-item">
                <a href="{% url 'amapp:my_sessions' request.session.register_id %}">
                    <div class="my-4 sidenav-active">
                        <i class="fas fa-calendar-alt"></i>
                        <h6>Sessions</h6>
                    </div>
                </a>
            </div>
        </div>
        <div id="workspace">
            <div class="row">
                <div class="col-6">
                    <h2>{{Context.Register.name}}</h2>
                    <h6>Register Id:&nbsp;<span class="blue">{{ Context.Register.reg_id }}</span></h6>
                </div>
                <div class="col-6 my-sm-4">
                    <button class="btn btn-primary float-right mx-sm-4" data-toggle="modal" data-target="#exampleModalCenter">Start a session&nbsp;<i class="fa fa-arrow-right" aria-hidden="true"></i></button>
                </div>
            </div>
            <table class="table table-hover table-responsive-sm">
                <caption>List of Sessions in this Register</caption>
                <thead>
                    <tr>
                        <th scope="col">s/n</th>
                        <th scope="col">Title</th>
                        <th scope="col">Date</th>
                        <th scope="col">Start</th>
                        <th scope="col">End</th>
                    </tr>
                </thead>
                <tbody>
                    {% for session in Context.Sessions %}
                    <tr>
                        <th scope="row">{{forloop.counter}}</th>
                        <td>{{session.title}}</td>
                        <td>{{session.date}}</td>
                        <td>{{session.start}}</td>
                        <td>{{session.end}}</td>
                        <td><a href="{% url 'amapp:session_details' request.session.register_id session.id %}">View</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div> 
    </div>
        <!------- Modal ----------->
        <div class="modal fade bd-example-modal-xl" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered modal-xl" role="document">
                <div class="modal-content">
                    <div class="row">
                        <div class="home col-lg-4">
                            <h1>ATTENDANCE<br><span class="smaller">MANAGEMENT</span><br>SYSTEM</h1>
                        </div>
                        <div class="home-right col-lg-8">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            <p class="buttonlike col-md-6 offset-md-3 mb-4">Start a session</p>
                            <form action="#">
                            <div class="form-group">
                                <input type="text" placeholder="Register Name" class="form-control">
                            </div>
                            <div class="form-group">
                                <input type="text" placeholder="Devide Id" class="form-control">
                            </div>
                            <div class="form-row">
                                <div class="form-group col-sm-6">
                                    <label for="start-time">Start time</label>
                                    <input type="time" placeholder="Start time" class="form-control" id="start-time">
                                </div>
                                <div class="form-group col-sm-6">
                                    <label for="end-time">End time</label>
                                    <input type="time" placeholder="End time" class="form-control" id="end-time">
                                </div>
                              </div>
                            <div class="form-group">
                                <input type="password" placeholder="Password" class="form-control">
                            </div>
                            <button type="submit" class="btn btn-primary">Start &nbsp;<i class="fa fa-arrow-right" aria-hidden="true"></i></button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            </div>
    </main>
{% endblock %}